/**
 * Redis Cache Configuration
 */
export const CACHE_CONFIG = {
  TTL: {
    ONE_HOUR: 3600,
    ONE_DAY: 86400,
    ONE_WEEK: 604800,
  },
  PREFIX: {
    USER: "user",
    TODO: "todo",
  },
} as const;

/**
 * Common Error Codes
 */
export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DUPLICATE_FIELD: "DUPLICATE_FIELD",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  DATABASE_REQUEST_ERROR: "DATABASE_REQUEST_ERROR",
  INVALID_REFERENCE: "INVALID_REFERENCE",
  CACHE_ERROR: "CACHE_ERROR",
  CACHE_CONNECTION_REFUSED: "CACHE_CONNECTION_REFUSED",
  CACHE_CONNECTION_CLOSED: "CACHE_CONNECTION_CLOSED",
  OPERATIONAL_ERROR: "OPERATIONAL_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;
